[package]
name = "gatelogue-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.9.2"

[dev-dependencies]
common = { path = "../gatelogue-common", package = "gatelogue-common" }

wasm-bindgen-test = "0.3.18"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']